print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/huwmessie/Documents/Unity/Boredom-Sim/BS/Assets/Models/desk.mb"`)
{		
	file -o "/Users/huwmessie/Documents/Unity/Boredom-Sim/BS/Assets/Models/desk.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/huwmessie/Documents/Unity/Boredom-Sim/BS/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/huwmessie/Documents/Unity/Boredom-Sim/BS/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/huwmessie/Documents/Unity/Boredom-Sim/BS/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
